version: '3'

services:
  postgres-prod:
    image: mdillon/postgis
    container_name: xyz
    ports:
      - "15432:5432"
    env_file:
      - ./credentials.env
    environment:
      - POSTGRES_PASSWORD=${PASS_PROD}
      - POSTGRES_USER=${USERNAME_PROD}
      - POSTGRES_DB=${DATABASE_PROD}
  postgres-test:
    image: mdillon/postgis
    container_name: xyz_test
    ports:
      - "8085:5432"
    env_file:
      - ./credentials_test.env
    environment:
      - POSTGRES_PASSWORD=${PASS_TEST}
      - POSTGRES_USER=${USERNAME_TEST}
      - POSTGRES_DB=${DATABASE_TEST}
