version: '3'

services:
  app:
    container_name: app-xyz
    build: ./
    image: elias/xyz
    ports:
      - 8080:8080
    depends_on:
      - db-prod
      - db-test
    env_file:
      - credentials.env
      - credentials_test.env
  db-prod:
    image: mdillon/postgis
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=xyz_prod
  db-test:
    image: mdillon/postgis
    ports:
      - 15432:5432
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=xyz_test
