version: '3'

services:
  postgres-prod:
    image: mdillon/postgis
    container_name: xyz
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=xyz_prod
  postgres-test:
    image: mdillon/postgis
    container_name: xyz_test
    ports:
      - "8085:5432"
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=xyz_test
